//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by client_app.rc
//
#define ID_TRANSFER                     2
#define IDB_TRANSFER                    2
#define IDOK2                           2
#define IDB_LOGOUT                      2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CLIENT_DIALOG               102
#define IDS_CLIENT_DIALOG_CAPTION       103
#define IDR_MAINFRAME                   128
#define IDB_ICONS                       129
#define IDD_LOGIN_PAGE                  132
#define IDD_REGISTER_PAGE               134
#define IDB_ICONS_HC                    135
#define IDD_MODEL_PAGE                  135
#define IDD_FILE_TRANSFER_PAGE          137
#define IDD_SERVER_CONFIG_PAGE          139
#define IDD_FILE_SERIVCE_PAGE           140
#define IDD_EVALUATE_PAGE               142
#define IDD_EVALUTE_RESULT_DLG          143
#define IDD_IMAGE_SHOW_DLG              144
#define IDD_EVALUTE_SHOW_DLG            145
#define IDC_LOGIN_NAME                  1001
#define IDC_LOGIN_PASSWORD              1002
#define IDC_LOGIN_PASSWORD_TITLE        1003
#define IDC_LOGIN_NAME_TITLE            1004
#define IDC_REGISTER_GROUP              1005
#define IDC_REGISTER_CONFIRM_PASSWORD_TITLE 1006
#define IDC_REGISTER_CONFIRM_PASSWORD   1007
#define IDC_REGISTER_NAME               1008
#define IDC_REGISTER_PASSWORD           1009
#define IDC_REGISTER_PASSWORD_TITLE     1010
#define IDC_REGISTER_NAME_TITLE         1011
#define IDC_LOGIN_GROUP                 1012
#define IDC_FILE_LIST                   1013
#define IDC_FILE_TRANSFER_PROGRESS      1014
#define IDC_FILE_TRANSFER_GROUP         1016
#define IDC_UPLOAD_BUTTON               1017
#define IDC_DOWNLOAD_BUTTON             1018
#define IDC_UPDATE_FILE_LIST_BUTTON     1020
#define IDC_SERVER_CONFIG_GROUP         1021
#define IDC_SERVER_CONFIG_IP_TEXT       1022
#define IDC_SERVER_CONFIG_IP_TEXT2      1023
#define IDC_SERVER_CONFIG_PORT_TEXT     1024
#define IDC_SERVER_CONFIG_PORT          1025
#define IDC_SERVER_CONFIG_PORT_TEXT2    1026
#define IDC_SERVER_CONFIG_IP            1027
#define ID                              1028
#define IDB_MODEL                       1028
#define IDC_FILE_SERVICE_MODEL_PORT     1028
#define IDC_FILE_SERVICE_MODEL_IP       1029
#define IDC_FILE_SERVICE_ROOT_PATH_TEXT 1030
#define IDC_FILE_SERVICE_ROOT_PATH      1031
#define IDC_FILE_SERVICE_FILE_SERVER_PORT 1032
#define IDC_FILE_SERVICE_FILE_SERVER_IP 1033
#define IDC_ALGORITHM_LIST              1034
#define IDC_RUNTIME_GROUP               1035
#define IDC_ALGORITHM_NAME              1036
#define IDC_ALGORITHM_NAME_STATIC       1037
#define IDC_ALGORITHM_FILE_PATH         1038
#define IDC_ALGORITHM_FILE_PATH_STATIC  1039
#define IDC_ALGORITHM_ADD_UPDATE        1040
#define IDC_ALGORITHM_DELETE            1041
#define IDC_EVALUATE_GROUP              1042
#define IDC_FACTOR_LIST                 1043
#define IDC_FACTOR_ADD_UPDATE           1044
#define IDC_FACTOR_DELETE               1045
#define IDC_FACTOR_NAME_STATIC          1046
#define IDC_FACTOR_NAME                 1047
#define IDC_FACTOR_DLL_PATH_STATIC      1048
#define IDC_FACTOR_DLL_PATH             1049
#define IDC_FACTOR_ALGORITHM_OUTPUT_STATIC 1050
#define IDC_FACTOR_ALGORITHM_OUTPUT     1051
#define IDC_FACTOR_ALGORITHM_OUTPUT_START 1052
#define IDC_FACTOR_ALGORITHM_OUTPUT_END 1053
#define IDC_FACTOR_ORIGIN_STATIC        1054
#define IDC_FACTOR_ORIGIN               1055
#define IDC_FACTOR_ORIGIN_START         1056
#define IDC_FACTOR_ORIGIN_END           1057
#define IDC_FACTOR_ALGORITHM_OUTPUT_START_STATIC 1058
#define IDC_FACTOR_ALGORITHM_OUTPUT_END_STATIC 1059
#define IDC_ALGORITHM_RUNTIME_RESULT_GROUP 1059
#define IDC_FACTOR_ORIGIN_START_STATIC  1060
#define IDC_ALGORITHM_RUNTIME_LIST      1060
#define IDC_FACTOR_ORIGIN_END_STATIC    1061
#define IDC_FACTOR_GROUP                1061
#define IDC_FACTOR_TRUE_VALUE_STATIC    1062
#define IDC_LOAD                        1063
#define IDC_SAVE                        1064
#define IDC_IMAGE_SHOW_GROUP            1065
#define IDC_FACTOR_TRUE_VALUE           1065
#define IDC_IMAGE                       1066
#define IDC_FACTOR_WINDOW_CENTER_STATIC 1066
#define IDC_SELECT_PATH                 1067
#define IDC_FACTOR_WINDOW_CENTER        1067
#define IDC_FILE_NAME_STATIC            1068
#define IDC_START_PAUSE_BUTTON          1069
#define IDC_INTERVAL                    1070
#define IDC_INTERVAL_STATIC             1071
#define IDC_NEXT_BUTTON                 1072
#define IDC_PREV_BUTTON                 1073
#define IDC_ALGORITHM_RUNTIME_GRP       1073
#define IDC_ALGORITHM_INFO              1074
#define IDC_IMG_0_0                     1075
#define IDC_IMG_0_1                     1076
#define IDC_IMG_1_0                     1077
#define IDC_IMG_1_1                     1078
#define IDC_ALGORITHM_INPUT_OUTPUT_GRP  1079
#define IDC_TIME_STC                    1080
#define IDC_TIME_TEXT                   1081
#define IDC_CPU_STC                     1082
#define IDC_CPU_TEXT                    1083
#define IDC_MEMORY_STC                  1084
#define IDC_MEMORY_TEXT                 1085
#define IDC_NS_STC                      1086
#define IDC_CPU_TEXT3                   1087
#define IDC_NS_TEXT                     1087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
